defmodule AgentManagerWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :agent_manager

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_agent_manager_key",
    signing_salt: "dP7/ToMO",
    same_site: "Lax"
  ]

  # peer_data + x_headers give the client IP for the token lockout
  socket "/socket", AgentManagerWeb.UserSocket,
    websocket: [connect_info: [:peer_data, :x_headers]],
    longpoll: false

  # socket "/live", Phoenix.LiveView.Socket,
  #   websocket: [connect_info: [session: @session_options]],
  #   longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :agent_manager,
    gzip: not code_reloading?,
    only: AgentManagerWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    body_reader: {AgentManagerWeb.Plugs.CacheBodyReader, :read_body, []},
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug :route

  # An app built on the engine routes its own paths first and forwards the
  # rest to `AgentManagerWeb.Router`:
  #
  #     config :agent_manager, router: MyAppWeb.Router
  #
  # Looked up per request: the engine compiles before the app that configures
  # it, so the router can't be initialised at compile time.
  defp route(conn, _opts) do
    router = Application.get_env(:agent_manager, :router, AgentManagerWeb.Router)
    router.call(conn, router.init([]))
  end
end
